import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "@/components/NavBar";
import { Toaster } from "react-hot-toast";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}
      >
        <ClerkProvider>
          <div className="flex h-full  bg-gradient-to-b from-black to-gray-900  flex-col gap-1 ">
            <Navbar />
            <div className="pt-[80px] ">
              {children}
            </div>
          </div>

          <Toaster />
        </ClerkProvider>

      </body>
    </html>
  );
}
